### PR TITLE
Remove the URL schemes from mirrors

### PR DESCRIPTION
**Pull request by MichaIng**
as of: https://github.com/armbian/dl-router/pull/14

And fix a syntax error introduced in this PR on the scheme check.

### CODE REVIEW

**Comment by lanefu** [comment]
i made a development branch we can PR against for other work

**Comment by MichaIng** [comment]
Good idea, I started using such on all my active projects as well.

**Comment by lanefu** [comment]
okay I've rolled it out.. seems to work.. 1 slight bug that do need to fix..

https://github.com/armbian/dl-router/blob/master/app/main.py#L118

needs to return list with http:// prefixed so that the mirror selection tool in Armbian-config works...

any thoughts for quick fix for that?

**Comment by MichaIng** [comment]
Previously the scheme from the list was used, so `https://` would do as well, right? Generally I'd suggest to append the scheme in the `armbian-config` tool, probably even let the user choose whether to use HTTP or HTTPS? I can send a PR.

But as the router is live already, a package upgrade won't be released quickly and we do not want to break older `armbian-config` versions either, I agree we should work around it in the router as well.

First of all, there was one mirror which had `http://` prefix (though it supports HTTPS, even with HSTS header), all others `https://`. So I guess HTTPS is generally fine, right? I personally don't see any reason to keep using HTTP even that APT implies another authenticity check. The request to install the trusted APT key could be faked, so good practice to ban plain HTTP everywhere 😄.

**Comment by lanefu** [comment]
given lessons learned recently, set it to HTTP, for now.. yeah we're too close to a release for armbian-config change.. plus need backwards compatible solution.

**Comment by MichaIng** [comment]
Patch up: #16

**Comment by MichaIng** [comment]
@lanefu 
Was this change reverted or an old version uploaded? We have a new reports of the same issue, HTTPS being redirected to HTTP, more precisely `https://apt.armbian.com` => `http://armbian.hosthatch.com`. I see it is a new mirror and I see it supports HTTPS. Has it probably been added to the mirror list with `http://` scheme? As it supports HTTPS, I suggest to remove the scheme 😉.

**Comment by lanefu** [comment]
@MichaIng thanks for the notice. will take a look..

**Comment by lanefu** [comment]
@MichaIng oopps had wrong version of app deployed :). try now

**Comment by MichaIng** [comment]
@lanefu 
Hmm, I still get this error 🤔:
```
Err:9 https://apt.armbian.com buster/main arm64 Packages
  Redirection from https to 'http://armbian.hosthatch.com/apt/dists/buster/main/binary-arm64/Packages.xz' is forbidden
```
Same for other mirrors:
```
Err:8 https://apt.armbian.com buster/main armhf Packages
  Redirection from https to 'http://mirrors.netix.net/armbian/apt/dists/buster/main/binary-armhf/Packages.xz' is forbidden
```
So it seems like the mirrors all have a hardcoded plain `http://` scheme currently.

**Comment by lanefu** [comment]
Man i thought i tested this.  Ill dig in shortly

**Comment by lanefu** [comment]
@MichaIng fixed foreal this time.. I need to improve my deployment process.

are you on libera.chat?   would like to catch up with you sometime there. or our [armbian discord](https://docs.armbian.com/Community_IRC/#discord)

**Comment by MichaIng** [comment]
I just joined the Armbian discord channel, but I don't have it running constantly and couldn't find a way to enable mail notifications yet. Real somewhere that those are enabled by default but disabled permanently once connected via mobile app once 🤔.

**Pull request merged**
