### PR TITLE
Proposition to get a command line parameter for mirrors configuration file

### PR DESCRIPTION
**Pull request by jeanrhum**
I was not able to run the flask app, because of several requirements I was not able to install in my dev environment. However I tested the command line option string interpretation and I think the modification of the mirror class should be enough. Let me know if you have issues.

### CODE REVIEW

**Comment by lanefu** [comment]
Thanks @jeanrhum 

Since flask is being called at the command line for execution, I think some additional components would ahve to be used..

https://stackoverflow.com/questions/41264425/how-can-i-make-command-line-arguments-visible-to-flask-routes

honestly in hindsight, using environment variables may be easier than CLI arguments the more I think about it.

**Comment by jeanrhum** [comment]
Okay, but the link you give does not really promote environment variables. The initial post use a global python variable and in both codes they don't use more components than in the PR (sys package and argv values).

I tried to answer the example you use, but I have no real opinion if linux environment variables should be preferable as CLI arguments. If you prefer env vars, give an example and it should be quite easy as described here: https://www.nylas.com/blog/making-use-of-environment-variables-in-python/#:~:text=Environment%20variables%E2%80%94%20variables%20that%20exist,running%20your%20scripts%20and%20applications.

**Comment by lanefu** [comment]
Mostly I realized that the CLI arguments are coming in via flask, so unfortunately there's more glue involved than applying directly at the class.

What issues were you having with installing the flask dependencies?

**Comment by jeanrhum** [comment]
On two different config (armbian sbc and macos), I got the same error with uwsgi even if it is installed. I used instructions from the readme to run it locally:

```
(armbian) > $ pip install -r requirements.txt                                                                        [±master ✓]
Requirement already satisfied: flask in /Users/x/miniconda3/envs/armbian/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.1.2)
Requirement already satisfied: uwsgi in /Users/x/miniconda3/envs/armbian/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.0.19.1)
Requirement already satisfied: python-dotenv in /Users/x/miniconda3/envs/armbian/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.15.0)
Collecting ruamel.yaml
  Downloading ruamel.yaml-0.16.13-py2.py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 553 kB/s
Requirement already satisfied: maxminddb in /Users/x/miniconda3/envs/armbian/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.0.3)
Requirement already satisfied: maxminddb-geolite2 in /Users/x/miniconda3/envs/armbian/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2018.703)
Requirement already satisfied: itsdangerous>=0.24 in /Users/x/miniconda3/envs/armbian/lib/python3.7/site-packages (from flask->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: click>=5.1 in /Users/x/miniconda3/envs/armbian/lib/python3.7/site-packages (from flask->-r requirements.txt (line 1)) (7.1.2)
Requirement already satisfied: Jinja2>=2.10.1 in /Users/x/miniconda3/envs/armbian/lib/python3.7/site-packages (from flask->-r requirements.txt (line 1)) (2.11.3)
Requirement already satisfied: Werkzeug>=0.15 in /Users/x/miniconda3/envs/armbian/lib/python3.7/site-packages (from flask->-r requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/x/miniconda3/envs/armbian/lib/python3.7/site-packages (from Jinja2>=2.10.1->flask->-r requirements.txt (line 1)) (1.1.1)
Collecting ruamel.yaml.clib>=0.1.2
  Downloading ruamel.yaml.clib-0.2.2-cp37-cp37m-macosx_10_9_x86_64.whl (147 kB)
     |████████████████████████████████| 147 kB 551 kB/s
Installing collected packages: ruamel.yaml.clib, ruamel.yaml
Successfully installed ruamel.yaml-0.16.13 ruamel.yaml.clib-0.2.2

(armbian) > $ python3 -m flask run --host 0.0.0.0 --port 5000                                                        [±master ✓]
 * Serving Flask app "main"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: python -m flask run [OPTIONS]

Error: While importing "main", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/x/miniconda3/envs/armbian/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/x/Boulot/dev/armbian-dev/dl-router/app/main.py", line 5, in <module>
    import uwsgi
ModuleNotFoundError: No module named 'uwsgi'
```

**Comment by lanefu** [comment]
Okay I pushed an update to master that should resolve that bug.    Apparently uwsgi is only available when running under uwsgi...  I added a conditional import and that seemed to work.

I added a message that says `not running under uwsgi` when the import fails

```
lane@pineh64-b:~/GIT/ARMBIAN/dl-router/app$ FLASK_APP=./main.py python -m flask run --host 0.0.0.0 --port 5000
 * Serving Flask app "./main.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
not running under uwsgi
```

**Comment by jeanrhum** [comment]
Yep, I am able to run it now. I'll looked the way to pass argument to flask, but if you prefer an env variable it may be easier.

**Comment by lanefu** [comment]
> Yep, I am able to run it now. I'll looked the way to pass argument to flask, but if you prefer an env variable it may be easier.

yeah lets try environment variables.. I think it will make more sense overall.

**Comment by jeanrhum** [comment]
I made a new commit with ARMBIAN_MIRROR_CONF env variable and it works on my side.

**Comment by lanefu** [comment]
[AR-684]

[AR-684]: https://armbian.atlassian.net/browse/AR-684

**Comment by lanefu** [comment]
hopefully I'll test and rollout tonight.. thank you!

**Comment by lanefu** [comment]
functional requested seems fine.. I'm still fighting uwsgi, but that's a me problem.. thanks for the feature!

**Pull request merged**
